"""
convert_padeltracker100.py
==========================
Convert the PadelTracker100 (Zenodo) dataset from COCO-keypoint format to
YOLO detection format for PLAYER bounding-box training.

PadelTracker100 ships two full WPT matches as .mp4 + COCO JSON label files:
    *_pose.json   -> player annotations: bbox (x,y,w,h, abs px) + 17 COCO keypoints
    *_ball.json   -> ball bboxes   (not used here)
    *_shots.csv   -> shot events   (not used here)

This script:
  * opens each match video,
  * decodes a sampled subset of frames (--stride, to keep size manageable),
  * extracts player boxes from the *_pose.json annotations,
  * writes images (jpg) + YOLO .txt labels,
  * assigns FinalM -> train, FinalF -> val (no cross-match leakage).

Output:
    data/datasets/padeltracker100_yolo/
        images/{train,val}/*.jpg
        labels/{train,val}/*.txt
        data.yaml

Usage:
    python src/convert_padeltracker100.py --stride 6
    python src/convert_padeltracker100.py --stride 4 --quality 90
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import cv2

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW = PROJECT_ROOT / "data" / "datasets" / "padeltracker100" / "raw"
OUT = PROJECT_ROOT / "data" / "datasets" / "padeltracker100_yolo"

# (video filename, pose-json filename, split)
MATCHES = [
    ("2022_BCN_FinalM_1.mp4", "labels/2022_BCN_FinalM_1_pose.json", "train"),
    ("2022_BCN_FinalF_1.mp4", "labels/2022_BCN_FinalF_1_pose.json", "val"),
]

FRAME_RE = re.compile(r"frame_(\d+)", re.IGNORECASE)


def frame_index_from_image(img: dict) -> int:
    """Map a COCO image entry to its integer frame index in the video."""
    m = FRAME_RE.search(img.get("file_name", ""))
    if m:
        return int(m.group(1))
    return int(img["id"]) - 1  # fallback: id is 1-based


def coco_to_yolo_box(bbox, w, h):
    """[x,y,w,h] abs px -> (cx,cy,w,h) normalized, clamped to [0,1]."""
    x, y, bw, bh = bbox
    cx = min(max((x + bw / 2.0) / w, 0.0), 1.0)
    cy = min(max((y + bh / 2.0) / h, 0.0), 1.0)
    nw = min(max(bw / w, 0.0), 1.0)
    nh = min(max(bh / h, 0.0), 1.0)
    return cx, cy, nw, nh


def process_match(video_path: Path, json_path: Path, split: str,
                  stride: int, quality: int) -> tuple[int, int]:
    """Extract sampled frames + YOLO labels for one match. Returns (frames, boxes)."""
    print(f"[{split}] {video_path.name} <- {json_path.name}")
    data = json.load(open(json_path))
    W = data["images"][0]["width"]
    H = data["images"][0]["height"]

    # group annotations by image id
    ann_by_img: dict[int, list] = {}
    for a in data["annotations"]:
        ann_by_img.setdefault(a["image_id"], []).append(a)

    # build {frame_index: image} and keep only frames that have player boxes
    img_by_frame = {frame_index_from_image(im): im for im in data["images"]}

    targets = sorted(f for f, im in img_by_frame.items()
                     if im["id"] in ann_by_img)
    targets = targets[::stride]  # sample 1 every N

    img_dir = OUT / "images" / split
    lbl_dir = OUT / "labels" / split
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"cannot open video {video_path}")

    n_frames = 0
    n_boxes = 0
    target_set = set(targets)
    cur = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        if cur in target_set:
            im = next((v for k, v in img_by_frame.items() if k == cur), None)
            if im is not None:
                stem = f"{video_path.stem}_f{cur:06d}"
                jpg_path = img_dir / f"{stem}.jpg"
                lbl_path = lbl_dir / f"{stem}.txt"
                cv2.imwrite(str(jpg_path), frame, [int(cv2.IMWRITE_JPEG_QUALITY), quality])
                lines = []
                for a in ann_by_img.get(im["id"], []):
                    cx, cy, bw, bh = coco_to_yolo_box(a["bbox"], W, H)
                    if bw > 0.002 and bh > 0.002:  # drop degenerate boxes
                        lines.append(f"0 {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
                if lines:
                    lbl_path.write_text("\n".join(lines) + "\n")
                    n_frames += 1
                    n_boxes += len(lines)
                else:
                    jpg_path.unlink(missing_ok=True)  # no valid boxes -> drop image
        cur += 1
    cap.release()
    print(f"[{split}] wrote {n_frames} frames, {n_boxes} boxes")
    return n_frames, n_boxes


def write_data_yaml(total_frames: int) -> None:
    yaml = f"""# Auto-generated by src/convert_padeltracker100.py
# PadelTracker100 (Zenodo) -> YOLO player detection
path: {OUT}
train: images/train
val: images/val
test: images/val
nc: 1
names:
  0: player
"""
    (OUT / "data.yaml").write_text(yaml)
    print(f"[data.yaml] written ({total_frames} frames)")


def main() -> None:
    ap = argparse.ArgumentParser(description="Convert PadelTracker100 -> YOLO.")
    ap.add_argument("--stride", type=int, default=6,
                    help="keep 1 frame every N (6 -> ~9k/match).")
    ap.add_argument("--quality", type=int, default=88, help="jpg quality.")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for vid, js, split in MATCHES:
        vpath = RAW / vid
        jpath = RAW / js
        if not vpath.exists() or not jpath.exists():
            print(f"  skip missing: {vid} / {js}")
            continue
        nf, _ = process_match(vpath, jpath, split, args.stride, args.quality)
        total += nf
    write_data_yaml(total)


if __name__ == "__main__":
    main()
